### PR TITLE
Keys duplication

### PR DESCRIPTION
**Pull request by warlof**
This is an hotfix for Alliance Auth

### CODE REVIEW

**Comment by leonjza** [comment]
Why do we need to return the `user_id` here?

**Comment by leonjza** [comment]
I also think we should rather just `firstOrNew()` here and update the existing entry with the new data instead of adding the error condition.

**Comment by warlof** [comment]
Returning uid was a request from alliance Auth team

What would you want to update if the key already exists ?

**Comment by leonjza** [comment]
> What would you want to update if the key already exists ?

The owner mostly.

**Comment by leonjza** [comment]
I think it is going to be best to just return the error that the key already exists, and then have an API consumer use the normal [get](http://seat-docs.readthedocs.io/en/latest/seat_api/eve_api_keys/#get-a-single-eve-api-key) method to retrieve the details. Having arbitrary values like this return in an odd place makes the maintenance a little harder in the long term.

In short, I agree with the PR, but it should be updated to only return an error and not the owners `user_id` as well.

**Comment by herpaderpaldent** [comment]
Problem seems to persist: 

`Disabled due to possibly expired key. 403:Client error: `GET https://api.eveonline.com/account/APIKeyInfo.xml.aspx?keyID=6188200&vCode=XXXXXXXXXXXXXXXXXXXXXXXMJ` resulted in a `403 Forbidden` response:
<?xml version='1.0' encoding='UTF-8'?>
<eveapi version="2">
  <currentTime>2017-06-05 09:39:41</currentTime>
  <error (truncated...)`

**Comment by warlof** [comment]
That's not related to this Pr and it's totally normal that CCP return 403 for disabled keys.

**Pull request merged**
